# description
Basic data exploration of alerts data.

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
datapath = "../data/"
outputs = "../outputs/"

In [3]:
df_miraflores = pd.read_csv(os.path.join(datapath,'miraflores-alerts.csv'))
df_montevideo = pd.read_csv(os.path.join(datapath,'montevideo-alerts.csv'))

In [ ]:
dfs_dict = {}
dfs_dict = {"montevideo": df_montevideo, "miraflores": df_miraflores}

In [ ]:
df_miraflores.head()

In [13]:
df_miraflores.tail()

,uuid,latitude,longitude,type,subtype,interactions,street,reliability,start_time,end_time
32400,c737f453-8c2c-36d1-907a-775a5dd0969a,-12.125435,-77.012968,JAM,JAM_HEAVY_TRAFFIC,1,Av. General Ernesto Montagne,6,2019-07-02 00:26:00.000,2019-07-02 00:55:00.000
32401,b3d72185-8d2a-3add-ae57-34afc0afb8cb,-12.123239,-77.018999,JAM,JAM_MODERATE_TRAFFIC,1,Av. Ricardo Palma,5,2019-07-11 22:27:00.000,2019-07-11 22:32:00.000
32402,901be114-0347-3f30-aaaf-ad76e3fd6af1,-12.118998,-77.034579,JAM,JAM_MODERATE_TRAFFIC,1,Av. José Pardo,5,2019-07-04 13:09:00.000,2019-07-04 13:38:00.000
32403,eab7fc92-a02a-38f6-9a93-90436197a694,-12.128750,-77.016577,JAM,JAM_HEAVY_TRAFFIC,1,Manuel Augusto Olaechea,5,2019-07-02 00:47:00.000,2019-07-02 01:05:00.000
32404,58416dc7-8c12-3a2e-8763-298ddcc140b2,-12.124424,-77.030428,JAM,JAM_HEAVY_TRAFFIC,1,Av. Alfredo Benavides,6,2019-07-11 19:04:00.000,2019-07-11 19:33:00.000

In [14]:
df_montevideo.head()

,uuid,latitude,longitude,type,subtype,interactions,street,reliability,start_time,end_time
0,8462624d-5c9d-318a-823d-d53f785e495d,-34.907669,-56.176553,WEATHERHAZARD,HAZARD_ON_ROAD_POT_HOLE,108,Canelones,10,2019-07-07 13:10:00.000,2019-07-13 06:32:00.000
1,e9892303-a651-32cd-8399-5c5dd0c9bb8e,-34.923522,-56.161606,WEATHERHAZARD,HAZARD_ON_ROAD_POT_HOLE,90,Francisco García Cortinas,10,2019-07-16 22:26:00.000,2019-07-29 11:41:00.000
2,67f92a84-1a74-331c-8272-cb2330254283,-34.895943,-56.167902,WEATHERHAZARD,HAZARD_ON_ROAD_POT_HOLE,84,Daniel Muñoz,10,2019-07-18 14:26:00.000,2019-07-22 19:23:00.000
3,ecf70f1c-4b17-3410-91f9-a7efd7bf1aed,-34.875881,-56.180787,WEATHERHAZARD,HAZARD_ON_ROAD_POT_HOLE,76,Av. Gral. Garibaldi,10,2019-07-11 15:42:00.000,2019-07-17 21:41:00.000
4,5a0e0e71-d29d-3e28-bbed-e371580235e6,-34.893478,-56.159235,WEATHERHAZARD,HAZARD_ON_ROAD_POT_HOLE,73,Av. Dr. Américo Ricaldoni,10,2019-07-22 16:48:00.000,2019-07-26 20:36:00.000

In [15]:
df_montevideo.tail()

,uuid,latitude,longitude,type,subtype,interactions,street,reliability,start_time,end_time
26537,0e932b85-1e36-3d43-a9ce-95f7e5f424e2,-34.876336,-56.148672,ROAD_CLOSED,ROAD_CLOSED_EVENT,1,Carlos Crocker,6,2019-07-06 08:55:00.000,2019-07-06 17:56:00.000
26538,b62b3da1-7b4d-3356-9afa-444ec59d8c1a,-34.868936,-56.123807,ROAD_CLOSED,ROAD_CLOSED_EVENT,1,Pirán,6,2019-07-04 08:55:00.000,2019-07-04 16:56:00.000
26539,d5cba684-c2cc-3b6d-a5ca-75da556e121b,-34.818916,-56.214631,ROAD_CLOSED,ROAD_CLOSED_EVENT,1,Bv. Aparicio Saravia,6,2019-07-04 08:55:00.000,2019-07-04 17:56:00.000
26540,b1f5df16-dde6-3110-bdb5-74a2ead73901,-34.868061,-56.063304,WEATHERHAZARD,NaN,1,Cno. Carrasco,5,2019-07-23 18:56:00.000,2019-07-23 19:26:00.000
26541,1d519a85-2db8-3092-ac48-de214cdc1e1b,-34.906053,-56.193123,WEATHERHAZARD,HAZARD_ON_ROAD_CONSTRUCTION,1,Av. 18 de Julio,5,2019-07-30 12:28:00.000,2019-07-31 12:28:00.000

In [23]:
print("INFO:\n")
for name,df in dfs_dict.items():
    print(name.upper(), '\n')
    print(df.info(), '\n')

INFO:

MONTEVIDEO

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26542 entries, 0 to 26541
Data columns (total 10 columns):
uuid            26542 non-null object
latitude        26542 non-null float64
longitude       26542 non-null float64
type            26542 non-null object
subtype         24871 non-null object
interactions    26542 non-null int64
street          26198 non-null object
reliability     26542 non-null int64
start_time      26542 non-null object
end_time        26542 non-null object
dtypes: float64(2), int64(2), object(6)
memory usage: 2.0+ MB
None

MIRAFLORES

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32405 entries, 0 to 32404
Data columns (total 10 columns):
uuid            32405 non-null object
latitude        32405 non-null float64
longitude       32405 non-null float64
type            32405 non-null object
subtype         30961 non-null object
interactions    32405 non-null int64
street          32134 non-null object
reliability     32405 non-null int64
start_time      32405 non-null object
end_time        32405 non-null object
dtypes: float64(2), int64(2), object(6)
memory usage: 2.5+ MB
None

In [18]:
print("DESCRIPTION:\n")
for name,df in dfs_dict.items():
    print(name.upper(), '\n')
    print(df.describe(), '\n')

DESCRIPTION:

MONTEVIDEO

           latitude     longitude  interactions   reliability
count  26542.000000  26542.000000  26542.000000  26542.000000
mean     -34.879514    -56.166598      2.390965      6.074523
std        0.028245      0.040492      4.795191      1.515535
min      -34.929126    -56.350176      1.000000      5.000000
25%      -34.899780    -56.189392      1.000000      5.000000
50%      -34.887299    -56.165379      1.000000      6.000000
75%      -34.867615    -56.147680      1.000000      6.000000
max      -34.699358    -56.031563    108.000000     10.000000

MIRAFLORES

           latitude     longitude  interactions   reliability
count  32405.000000  32405.000000  32405.000000  32405.000000
mean     -12.119841    -77.027472      1.844839      5.827372
std        0.008257      0.010909      2.939573      1.477585
min      -12.169412    -77.055753      1.000000      5.000000
25%      -12.126514    -77.032454      1.000000      5.000000
50%      -12.120594    -77.028134      1.000000      5.000000
75%      -12.113341    -77.021434      1.000000      6.000000
max      -12.098063    -77.001493     63.000000     10.000000

In [21]:
print("VARIABLE CATEGORIES:\n")
for name,df in dfs_dict.items():
    print(name.upper(), '\n')
    for cat in df.columns:
        print("Number of levels in category '{0}': \b {1:2.2f} ".format(cat, df_miraflores[cat].unique().size))
    print("\n")

VARIABLE CATEGORIES:

MONTEVIDEO

Number of levels in category 'uuid':  32404.00
Number of levels in category 'latitude':  17008.00
Number of levels in category 'longitude':  18873.00
Number of levels in category 'type':  4.00
Number of levels in category 'subtype':  25.00
Number of levels in category 'interactions':  49.00
Number of levels in category 'street':  289.00
Number of levels in category 'reliability':  6.00
Number of levels in category 'start_time':  15643.00
Number of levels in category 'end_time':  15550.00


MIRAFLORES

Number of levels in category 'uuid':  32404.00
Number of levels in category 'latitude':  17008.00
Number of levels in category 'longitude':  18873.00
Number of levels in category 'type':  4.00
Number of levels in category 'subtype':  25.00
Number of levels in category 'interactions':  49.00
Number of levels in category 'street':  289.00
Number of levels in category 'reliability':  6.00
Number of levels in category 'start_time':  15643.00
Number of levels in category 'end_time':  15550.00

#correlation matrix
corrmat = df_miraflores.corr()
f, ax = plt.subplots(figsize=(12, 9))
sns.heatmap(corrmat, vmax=.8, square=True);

In [22]:
print("MISSING DATA:\n")
for name,df in dfs_dict.items():
    print(name.upper(), '\n')
    total = df.isnull().sum().sort_values(ascending=False)
    percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
    print(missing_data.head(10))

MISSING DATA:

MONTEVIDEO

              Total   Percent
subtype        1671  0.062957
street          344  0.012961
end_time          0  0.000000
start_time        0  0.000000
reliability       0  0.000000
interactions      0  0.000000
type              0  0.000000
longitude         0  0.000000
latitude          0  0.000000
uuid              0  0.000000
MIRAFLORES

              Total   Percent
subtype        1444  0.044561
street          271  0.008363
end_time          0  0.000000
start_time        0  0.000000
reliability       0  0.000000
interactions      0  0.000000
type              0  0.000000
longitude         0  0.000000
latitude          0  0.000000
uuid              0  0.000000